language: python

os:
  - linux
  - osx

python:
  - "pypy"
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

matrix:
  include:
  - python: "2.6"
    env: CRYPTOGRAPHY_GIT_MASTER=true
  - python: "2.7"
    env: CRYPTOGRAPHY_GIT_MASTER=true
  - python: "3.2"
    env: CRYPTOGRAPHY_GIT_MASTER=true
  - python: "3.3"
    env: CRYPTOGRAPHY_GIT_MASTER=true
  - python: "pypy"
    env: CRYPTOGRAPHY_GIT_MASTER=true
  allow_failures:
  - env: CRYPTOGRAPHY_GIT_MASTER=true

before_install:
  - if [ -n "$CRYPTOGRAPHY_GIT_MASTER" ]; then pip install git+https://github.com/pyca/cryptography.git;fi

install:
  # Install the wheel library explicitly here.  It is not really a setup
  # dependency.  It is not an install dependency.  It is only a dependency for
  # the script directive below - because we want to exercise wheel building on
  # travis.
  - pip install wheel

script:
  - python setup.py bdist_wheel test
